Gtk4 port
timholy/ProfileView.jl pull request #223
Opened 2023-07-02 13:10 UTC by jwahlstrand

Still to be sorted out:
* how to reliably pause the main loop during profiling
* zoomscroll does not work yet (a GtkObservable issue)

2024-01-19 15:00 UTC, nhz2 requested changes
Looks good with a few patches. I tested this on Windows using the default example. Here is a screenshot:
<img width="414" alt="image" src="https://github.com/timholy/ProfileView.jl/assets/39104088/7a3dc100-b238-4321-918e-9d2db729738b">

2024-01-19 15:00 UTC, nhz2 commented on Project.toml
> +Gtk4 = "0.5"
```suggestion
Gtk4 = "0.6"
```

2024-01-19 15:00 UTC, nhz2 commented on src/ProfileView.jl
> +            push!(tb, tb_text)
```suggestion
            tb_text.hexpand = true
```
Setting this prevented the text from getting cutoff.

2024-01-19 15:00 UTC, nhz2 commented on src/ProfileView.jl
> +            push!(tb, GtkSeparator(:h))
```suggestion
            push!(tb, GtkSeparator(:h))
            push!(tb, tb_text)
```
Moving `push!(tb, tb_text)` preserved the order of the toolbar.

2024-01-19 15:00 UTC, nhz2 commented on src/ProfileView.jl
> +        end
```suggestion
        if data === nothing && lidict === nothing
            _save(selection, g)
        else
            _save(selection, data, lidict)
        end
```
This fixes the saving functionality.

2024-01-19 22:20 UTC, jwahlstrand commented on Project.toml
> +Gtk4 = "0.5"
I'd like to keep 0.5 compat as well.

2024-01-19 22:59 UTC, nhz2 approved these changes
Looks good. I also tested on Linux using Pop!_OS 22.04.
Everything in the GUI works like in the previous version.

I get the warning:
```
(process:31294): Gtk-WARNING **: 17:38:16.184: No IM module matching GTK_IM_MODULE=ibus found
```
when opening the viewer, and the following when saving or opening a "testdata.jlprof" file.
```
(process:31294): Gtk-WARNING **: 17:46:52.667: Attempting to add 'file:///home/nathan/github/ProfileView.jl/testdata.jlprof' to the list of recently used resources, but no name of the application that is registering it was defined
```
But these don't seem to cause any issues.

![image](https://github.com/timholy/ProfileView.jl/assets/39104088/f5cedc0e-161f-4dbb-987f-070e9538dc60)

2024-01-19 23:25 UTC, jwahlstrand commented
I don't see those warnings on Fedora, but they're basically harmless. I wish GTK had a mechanism to silence stuff like that.

2024-08-05 02:05 UTC, IanButterworth commented
What's the status of this?

On MacOS it seems to work (though the text on the canvas is a little blurry?) and I see no terminal warnings.

![Screenshot 2024-08-04 at 10 04 31 PM](https://github.com/user-attachments/assets/e9b917a3-d6b4-43f8-9e17-bda458a63ba1)

2024-08-05 02:22 UTC, IanButterworth commented
I wonder if the low resolution issue I'm seeing is related to the failure of this test on MacOS.. perhaps the range of sz is too small
https://github.com/timholy/ProfileView.jl/blob/f3754d0d50344f0d708e20e61a4d0588eac59582/test/runtests.jl#L151-L159

2024-08-05 10:49 UTC, jwahlstrand commented
> I get the warning:
> 
> ```
> (process:31294): Gtk-WARNING **: 17:38:16.184: No IM module matching GTK_IM_MODULE=ibus found
> ```
> 
> when opening the viewer, and the following when saving or opening a "testdata.jlprof" file.
> 
> ```
> (process:31294): Gtk-WARNING **: 17:46:52.667: Attempting to add 'file:///home/nathan/github/ProfileView.jl/testdata.jlprof' to the list of recently used resources, but no name of the application that is registering it was defined
> ```

The second of these warnings should be gone in the most recent version of Gtk4.

2024-08-05 10:56 UTC, jwahlstrand commented
On the resolution issue, I wonder if the scaling should be modified for HiDPI displays? That's what GLMakie does.

2024-08-05 13:57 UTC, IanButterworth commented
Seems like the blurry text rendering is a known and unsolved issue https://gitlab.gnome.org/GNOME/gtk/-/issues/3787

If you think this is ready, I say we go ahead.

2024-08-05 14:43 UTC, timholy commented
Sorry for my inattention (too many updates needed for Julia 1.11 in the Revise/Cthulhu/SnoopCompile etc stack).

I'll start playing with this, but @jwahlstrand feel free to merge whenever you are ready (you have an invite now).

2024-08-05 15:11 UTC, jwahlstrand commented
Thanks, I'll check one more thing this evening. The weird thing about the font issue is, we're not using GTK to draw the text, it's all Cairo. For me, it's still quite readable, so I think it's worth going ahead.

I'll try to update Yggdrasil to GTK 4.14 soon.

2024-08-11 23:49 UTC, jwahlstrand commented
The CI error came back and I think it was happening because the Profile didn't contain much of anything on MacOS, for some reason. Increasing the number of iterations in the profiled function seems to have fixed it.

I'm seeing an issue locally, only on my Mac. When ProfileView precompiles, using it right away doesn't work. Sometimes the windows don't appear, sometimes I see the following error, no matter what I try to profile:
```
Warning: There were no samples collected.
│ Run your program longer (perhaps by running it multiple times),
│ or adjust the delay between samples with `Profile.init()`.
```

But if I quit Julia and restart it, ProfileView works fine. So it seems like precompiling is having some sort of side effect. It's puzzling because ImageView has similar precompile code and works fine. I want to look into this a bit more before merging.

2024-08-12 09:58 UTC, timholy commented
Thanks for your careful work here! I don't have a Mac, nor any good ideas except to wonder if Mac isn't using COW across forked processes? https://softwareengineering.stackexchange.com/questions/244664/global-variable-in-a-linux-shared-library

2024-08-12 12:21 UTC, IanButterworth commented
I think there's a bigger issue on macOS. See https://github.com/JuliaLang/julia/issues/53816#issuecomment-2283798709

2024-08-14 01:40 UTC, jwahlstrand commented
I commented out the precompile code that causes issues on my Mac (which involves observable handlers). I don't notice any difference in performance so I'm going to merge this PR and investigate later.

2024-08-14 01:43 UTC, merged

2024-08-14 08:03 UTC, timholy commented
Thank you @jwahlstrand ! You're a true hero!